### PR TITLE
Refactor/total3 data route

### PR DESCRIPTION
**Pull request by agusbusta**
Refactor the total3 data route to OHLC model

### CODE REVIEW

**Comment by agusbusta** [comment]
Fixed! Let me know @daviddflix

**Comment by daviddflix** [comment]
## General Feedback

Here are my main observations:

**SQLAlchemyError exception:**
- As there is no database transaction there is no need for this exception.

**Line 93:**
This line is executing the get_total_3_data, this should be removed as it will execute the function when the server restarts.

**Imports:**
- The Blueprint is not being imported

Requirements:
- New Libraries should be added to the requirements.txt for fast installation and used of docker.

**Comment by daviddflix** [comment]
Feedback

Hey @agusbustadev,

Great work on the implementation—it’s much improved! There are just a few minor details to address:

Requirements
- **Library Management:** Please add any new libraries to requirements.txt to ensure smooth installation, especially when using Docker.

**Imports**
- **Code Cleanup:** Remove any unnecessary imports from both charts.py and total3.py to keep the codebase clean and efficient.

**New Parameter**
- **Scalability Enhancement:** To make the endpoint more scalable, consider adding a new integer parameter to allow the client to specify the number of days. The default should remain 15 days, as it currently is.
 
Let me know if you have any questions or need further assistance with these changes. Thanks for your hard work!

**Comment by agusbusta** [comment]
Fixed last changes!

**Review by daviddflix — APPROVED** [review]
Hey @agusbustadev really good work on this task!

**Pull request merged**
